"""Story scene extender — generates a sequel scene input file from a previous one.

Usage:
    python -m my_code.extend story_00.md --brief "Lyra and Aldric find a sealed chamber"
    python -m my_code.extend story_00.md --brief "..." --output story_01.md
    python -m my_code.extend story_00.md --brief "..." --beats 5

The output file inherits all static sections (narrator-prompt, writing-style,
world-info, author-note, character cards) from the previous file. New sections
(prior-context, scene-setup, scenario, scene-beats, writing-instructions) are
generated by an LLM from the user's brief and the previous file's content.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from my_code.agents.scene_extender import create_scene_extender
from my_code.parser import get_raw_sections, parse_scene_file


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _auto_output_path(prev_path: Path) -> Path:
    """Derive the next numbered path: story_00.md → story_01.md."""
    stem = prev_path.stem
    m = re.match(r'^(.+?)_(\d+)$', stem)
    if m:
        prefix, num_str = m.group(1), m.group(2)
        next_num = int(num_str) + 1
        next_stem = f"{prefix}_{str(next_num).zfill(len(num_str))}"
    else:
        next_stem = f"{stem}_01"
    return prev_path.parent / f"{next_stem}{prev_path.suffix}"


# ---------------------------------------------------------------------------
# File assembly
# ---------------------------------------------------------------------------

def _build_meta_block(prev_meta, new_title: str, output_path: Path) -> str:
    story_output = f"output/{output_path.stem}.md"
    lines = [
        f"title: {new_title}",
        f"version: {prev_meta.version}",
        f"mode: {prev_meta.mode}",
        f"pause_at: {prev_meta.pause_at}",
        f"output_file: {story_output}",
        f"output_format: {prev_meta.output_format}",
        f"pov: {prev_meta.pov}",
        f"target_length: {prev_meta.target_length}",
        f"language: {prev_meta.language}",
        f"nsfw: {str(prev_meta.nsfw).lower()}",
    ]
    return "\n".join(lines)


def _assemble_file(
    raw_sections: dict[str, str],
    prev_meta,
    new_title: str,
    output_path: Path,
    generated: dict,
) -> str:
    parts: list[str] = []

    def section(name: str, content: str) -> None:
        parts.append(f"[{name}]\n{content.strip()}\n")

    # --- Meta (updated title + output_file, rest inherited) ---
    section("meta", _build_meta_block(prev_meta, new_title, output_path))

    # --- Static sections copied verbatim ---
    for name in ("narrator-prompt", "writing-style"):
        if name in raw_sections:
            section(name, raw_sections[name])

    if "author-note" in raw_sections:
        section("author-note", raw_sections["author-note"])

    if "world-info" in raw_sections:
        section("world-info", raw_sections["world-info"])

    # Character cards (all, in order)
    char_keys = sorted(
        [k for k in raw_sections if k.startswith("character-")],
        key=lambda k: int(k.split("-")[1]),
    )
    for key in char_keys:
        section(key, raw_sections[key])

    # --- Generated sections ---
    section("prior-context", generated["prior_context"])

    setup = generated["scene_setup"]
    setup_lines = []
    for field in ("location", "time", "atmosphere"):
        if setup.get(field):
            setup_lines.append(f"{field}: {setup[field]}")
    section("scene-setup", "\n".join(setup_lines))

    section("scenario", generated["scenario"])

    beats_blocks: list[str] = []
    for i, beat in enumerate(generated["scene_beats"], 1):
        text = beat["text"].strip()
        block = f"{i}. {text}"
        if beat.get("pause"):
            block += "\n   [pause]"
        beats_blocks.append(block)
    section("scene-beats", "\n\n".join(beats_blocks))

    if generated.get("writing_instructions"):
        section("writing-instructions", generated["writing_instructions"])

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# LLM call
# ---------------------------------------------------------------------------

def _call_extender(prev_raw: str, brief: str, beats: int) -> dict:
    """Call the SceneExtenderAgent and parse its JSON output."""
    prompt = (
        f"## Previous Scene File\n\n{prev_raw}\n\n"
        f"## Brief for the Next Part\n\n{brief}\n\n"
        f"Generate the next scene with exactly {beats} beats."
    )

    agent = create_scene_extender()
    result = str(agent(prompt))

    # Extract JSON — local models sometimes wrap output in prose
    json_start = result.find("{")
    json_end = result.rfind("}") + 1
    if json_start < 0 or json_end <= json_start:
        raise ValueError(f"SceneExtender returned no JSON.\nRaw output:\n{result[:500]}")

    return json.loads(result[json_start:json_end])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Generate a sequel scene input file from a previous one."
    )
    parser.add_argument("previous", help="Path to the previous scene .md file")
    parser.add_argument("--brief", required=True, help="What happens in the next part")
    parser.add_argument("--output", help="Output path for the new scene file (auto-derived if omitted)")
    parser.add_argument("--beats", type=int, default=5, help="Number of beats to generate (default: 5)")
    args = parser.parse_args(argv)

    prev_path = Path(args.previous)
    if not prev_path.exists():
        print(f"Error: file not found: {prev_path}", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output) if args.output else _auto_output_path(prev_path)
    if output_path.exists():
        print(f"Warning: output file already exists and will be overwritten: {output_path}")

    print(f"Extending: {prev_path} → {output_path}")
    print(f"Brief: {args.brief[:80]}{'...' if len(args.brief) > 80 else ''}")

    # Load previous scene
    prev_meta = parse_scene_file(str(prev_path)).meta
    raw_sections = get_raw_sections(str(prev_path))
    prev_raw = prev_path.read_text(encoding="utf-8")

    # Generate new sections
    print("Calling SceneExtender agent...")
    generated = _call_extender(prev_raw, args.brief, args.beats)

    new_title = generated.get("title", f"{prev_meta.title} (continued)")
    print(f"Generated title: {new_title}")

    # Assemble and write
    content = _assemble_file(raw_sections, prev_meta, new_title, output_path, generated)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"Written: {output_path}")


if __name__ == "__main__":
    main()
