DIMENSIONS = {
    "archetype": {
        "label": "Archetype",
        "required": True,
        "options": [
            "Best Friend",
            "Mentor",
            "Rival",
            "Wise Elder",
            "Stranger on Train",
            "Crush",
            "Sibling",
            "Therapist",
            "Comedian",
            "Life Coach",
        ],
    },
    "gender": {
        "label": "Gender",
        "required": False,
        "options": ["Male", "Female", "Neutral", "Not Applicable"],
    },
    "energy": {
        "label": "Energy / Mood",
        "required": True,
        "options": ["Normal", "Chill", "Hyper", "Grumpy", "Melancholic", "Excited", "Sleepy", "Anxious", "Sarcastic", "Nostalgic"],
    },
    "talk_type": {
        "label": "Talk-Type",
        "required": True,
        "options": [
            "Timepass",
            "Deep Talk",
            "Roast",
            "Gossip",
            "Rant Mode",
            "Debate",
            "Teach Me",
            "Advice",
            "Brainstorm",
            "Storytelling",
            "Confess",
        ],
    },
    "region": {
        "label": "Region / Culture",
        "required": False,
        "options": [
            "India (General)",
            "South Indian",
            "North Indian",
            "US",
            "UK",
            "Gen Z Global",
            "Boomer",
            "Japanese",
        ],
    },
    "domain": {
        "label": "Domain / Passion",
        "required": False,
        "options": [
            "Tech Geek",
            "Foodie",
            "Filmy",
            "Fitness Bro",
            "Spiritual",
            "Sports",
            "Art / Music",
            "Political",
        ],
    },
    "language_style": {
        "label": "Language Style",
        "required": False,
        "options": [
            "Pure English",
            "Hinglish",
            "Tamil-English",
            "Formal",
            "Street Slang",
            "Regional Casual",
        ],
    },
    "familiarity": {
        "label": "Relationship Familiarity",
        "required": False,
        "options": [
            "First Meeting",
            "Acquaintance",
            "Old Friend",
            "Close Confidant",
        ],
    },
    "situation": {
        "label": "Situational Context",
        "required": False,
        "options": [
            "Late Night Can't Sleep",
            "Stuck at Airport",
            "Post-match / Post-movie",
            "Monday Morning",
            "Rainy Day",
            "Road Trip",
        ],
    },
    "emotional_need": {
        "label": "Emotional Need",
        "required": False,
        "options": [
            "Just Vibe",
            "Hype Me Up",
            "Challenge Me",
            "Vent Listener",
            "Distract Me",
        ],
    },
    "chat_medium": {
        "label": "Chat Medium",
        "required": True,
        "options": [
            "F2F (In Person)",
            "DM / Text Chat",
            "Voice Note",
            "Group Chat",
            "Mirror Image",
            "Inner Voice",
            "Dream State",
            "Letters / Postcards",
            "Confessional",
            "Parallel Universe",
        ],
    },
}

PRESETS: dict[str, dict[str, str]] = {
    # ── Simple / everyday ──────────────────────────────────────────
    "Chai Break": {
        "archetype": "Best Friend",
        "energy": "Chill",
        "talk_type": "Timepass",
        "chat_medium": "F2F (In Person)",
        "region": "India (General)",
        "language_style": "Hinglish",
        "familiarity": "Old Friend",
    },
    "Late Night": {
        "archetype": "Mentor",
        "energy": "Melancholic",
        "talk_type": "Deep Talk",
        "chat_medium": "DM / Text Chat",
        "situation": "Late Night Can't Sleep",
        "emotional_need": "Just Vibe",
    },
    "Wise Grandpa": {
        "archetype": "Wise Elder",
        "energy": "Chill",
        "talk_type": "Advice",
        "chat_medium": "F2F (In Person)",
        "domain": "Spiritual",
        "familiarity": "Old Friend",
    },
    "Road Trip": {
        "archetype": "Best Friend",
        "energy": "Excited",
        "talk_type": "Gossip",
        "chat_medium": "F2F (In Person)",
        "situation": "Road Trip",
        "language_style": "Regional Casual",
        "familiarity": "Old Friend",
        "emotional_need": "Distract Me",
    },
    # ── Fun / classic ──────────────────────────────────────────────
    "South Indian Gossip": {
        "archetype": "Best Friend",
        "energy": "Hyper",
        "talk_type": "Gossip",
        "chat_medium": "Group Chat",
        "region": "South Indian",
        "domain": "Filmy",
        "language_style": "Tamil-English",
        "familiarity": "Old Friend",
    },
    "Roast Session": {
        "archetype": "Sibling",
        "energy": "Hyper",
        "talk_type": "Roast",
        "chat_medium": "Voice Note",
        "language_style": "Street Slang",
        "familiarity": "Close Confidant",
    },
    "Debate Club": {
        "archetype": "Rival",
        "energy": "Hyper",
        "talk_type": "Debate",
        "chat_medium": "F2F (In Person)",
        "domain": "Political",
        "language_style": "Pure English",
    },
    # ── Peculiar / imaginative ─────────────────────────────────────
    "Shadow Self": {
        "archetype": "Life Coach",
        "energy": "Anxious",
        "talk_type": "Deep Talk",
        "chat_medium": "Mirror Image",
        "emotional_need": "Challenge Me",
    },
    "Dream Diary": {
        "archetype": "Wise Elder",
        "energy": "Nostalgic",
        "talk_type": "Storytelling",
        "chat_medium": "Dream State",
        "situation": "Late Night Can't Sleep",
        "emotional_need": "Distract Me",
    },
    "Other Me": {
        "archetype": "Stranger on Train",
        "energy": "Melancholic",
        "talk_type": "Brainstorm",
        "chat_medium": "Parallel Universe",
        "familiarity": "Acquaintance",
        "emotional_need": "Challenge Me",
    },
    "Confession Box": {
        "archetype": "Therapist",
        "energy": "Normal",
        "talk_type": "Confess",
        "chat_medium": "Confessional",
        "familiarity": "First Meeting",
        "emotional_need": "Vent Listener",
    },
    "Pen Pal": {
        "archetype": "Mentor",
        "energy": "Nostalgic",
        "talk_type": "Storytelling",
        "chat_medium": "Letters / Postcards",
        "familiarity": "Acquaintance",
        "language_style": "Formal",
    },
    # ── NSFW (set Content Level to No Control) ─────────────────────
    "2AM Texts": {
        "nsfw_level": "no-control",
        "archetype": "Crush",
        "energy": "Melancholic",
        "talk_type": "Confess",
        "chat_medium": "DM / Text Chat",
        "familiarity": "Close Confidant",
        "situation": "Late Night Can't Sleep",
        "emotional_need": "Just Vibe",
    },
    "Drunk Voice Note": {
        "nsfw_level": "no-control",
        "archetype": "Best Friend",
        "energy": "Hyper",
        "talk_type": "Rant Mode",
        "chat_medium": "Voice Note",
        "language_style": "Street Slang",
        "familiarity": "Close Confidant",
        "emotional_need": "Hype Me Up",
    },
    "Train Stranger": {
        "nsfw_level": "no-control",
        "archetype": "Stranger on Train",
        "energy": "Excited",
        "talk_type": "Timepass",
        "chat_medium": "F2F (In Person)",
        "familiarity": "First Meeting",
        "situation": "Stuck at Airport",
        "emotional_need": "Distract Me",
    },
}
