DIMENSIONS = {
    "archetype": {
        "label": "Archetype",
        "required": True,
        "options": [
            "Best Friend",
            "Mentor",
            "Rival",
            "Wise Elder",
            "Stranger on Train",
            "Crush",
            "Sibling",
        ],
    },
    "energy": {
        "label": "Energy / Mood",
        "required": True,
        "options": ["Chill", "Hyper", "Grumpy", "Melancholic", "Excited", "Sleepy"],
    },
    "talk_type": {
        "label": "Talk-Type",
        "required": True,
        "options": [
            "Timepass",
            "Deep Talk",
            "Roast",
            "Gossip",
            "Rant Mode",
            "Debate",
            "Teach Me",
            "Advice",
        ],
    },
    "region": {
        "label": "Region / Culture",
        "required": False,
        "options": [
            "India (General)",
            "South Indian",
            "North Indian",
            "US",
            "UK",
            "Gen Z Global",
            "Boomer",
            "Japanese",
        ],
    },
    "domain": {
        "label": "Domain / Passion",
        "required": False,
        "options": [
            "Tech Geek",
            "Foodie",
            "Filmy",
            "Fitness Bro",
            "Spiritual",
            "Sports",
            "Art / Music",
            "Political",
        ],
    },
    "language_style": {
        "label": "Language Style",
        "required": False,
        "options": [
            "Pure English",
            "Hinglish",
            "Tamil-English",
            "Formal",
            "Street Slang",
            "Regional Casual",
        ],
    },
    "familiarity": {
        "label": "Relationship Familiarity",
        "required": False,
        "options": [
            "First Meeting",
            "Acquaintance",
            "Old Friend",
            "Close Confidant",
        ],
    },
    "situation": {
        "label": "Situational Context",
        "required": False,
        "options": [
            "Late Night Can't Sleep",
            "Stuck at Airport",
            "Post-match / Post-movie",
            "Monday Morning",
            "Rainy Day",
            "Road Trip",
        ],
    },
    "emotional_need": {
        "label": "Emotional Need",
        "required": False,
        "options": [
            "Just Vibe",
            "Hype Me Up",
            "Challenge Me",
            "Vent Listener",
            "Distract Me",
        ],
    },
}

PRESETS: dict[str, dict[str, str]] = {
    "Chai Break": {
        "archetype": "Best Friend",
        "energy": "Chill",
        "talk_type": "Timepass",
        "region": "India (General)",
        "language_style": "Hinglish",
    },
    "Late Night": {
        "archetype": "Mentor",
        "energy": "Melancholic",
        "talk_type": "Deep Talk",
        "situation": "Late Night Can't Sleep",
        "emotional_need": "Just Vibe",
    },
    "Debate Club": {
        "archetype": "Rival",
        "energy": "Hyper",
        "talk_type": "Debate",
        "domain": "Political",
        "language_style": "Pure English",
    },
    "South Indian Gossip": {
        "archetype": "Best Friend",
        "energy": "Hyper",
        "talk_type": "Gossip",
        "region": "South Indian",
        "domain": "Filmy",
        "language_style": "Tamil-English",
        "familiarity": "Old Friend",
    },
    "Roast Me": {
        "archetype": "Sibling",
        "energy": "Hyper",
        "talk_type": "Roast",
        "language_style": "Street Slang",
        "familiarity": "Close Confidant",
    },
    "Wise Grandpa": {
        "archetype": "Wise Elder",
        "energy": "Chill",
        "talk_type": "Advice",
        "domain": "Spiritual",
        "familiarity": "Old Friend",
    },
}
